In [14]:
import warnings
warnings.filterwarnings('ignore')

In [15]:
%%capture
%%bash
git clone https://github.com/dmis-lab/biobert.git       #clone biobert repo
gdown --id 1R84voFKHfWV9xjzeLzWBbmY1uOMYpnyD            #download biobert embeddings
gdown --id 1ZEmMGZCBsfeeFrrJs2uUHK8mzzuNkzTR            #download medline dataset
tar -xzvf "biobert_v1.1_pubmed.tar.gz" -C "./biobert/"  #unzip biobert embeddings into repo


In [16]:
%%capture
%%bash
cd biobert
gdown --id 1n7-fIN7hTCkTMCXyZZw9kBHkyYGdgdGC            #download medline_re.py
./download.sh                                           #download test datasets
wait
pip install -r requirements.txt                         #install required packages
pip install pandas                                      #install pandas
pip install scikit-learn                                #install scikit-learn
pip install transformers                                #install transformers

In [17]:
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
import os
import sklearn

In [18]:
def annotate_sentence(s):
    #Annotates Sentence by replacing words with respective tags and the rest with Os
    #Example Input: <TREAT> Intravenous immune globulin </TREAT> for <DIS> recurrent spontaneous abortion </DIS> .
    #Example Output: ['B-TREAT', 'I-TREAT', 'I-TREAT', O, 'B-DIS', 'I-DIS', 'I-DIS', O]
    s = s.split(' ')
    subtag = []
    for x in range(len(s)):
        m = re.match('<(.*?)>', s[x])
        if m:
            subtag.append([x, m.group(1).replace('/', '')])
    subtag_index =  [[x[0], y[0], reduce_tag(x[1])] for x, y in zip(subtag[::2], subtag[1::2])]
    subtag_loc = [x[0] for x in subtag]
    replaced = []
    for x in subtag_index:
        for z,y in enumerate(range(x[0]+1, x[1]),1):
            s[y] = f"{'B' if z == 1 else 'I'}-{x[2]}"
            replaced.append(y)
    replaced_tags = replaced + subtag_loc
    retag = [y for y in [x for x in range(len(s))] if y not in replaced_tags]
    for x in retag:
        s[x] = 'O'
    for x in subtag_loc[::-1]:
        del s[x]
    return s
    
def reduce_tag(x):
    return 'DIS' if 'DIS' in x else 'TREAT' if 'TREAT' in x else None
def clean_labels(data):
    """
    Take raw dataframe and blend labels together. Remove TO_SEE instances.
    Input:
        Data: Pandas Dataframe
    Output:
        Data: Pandas Dataframe
    """
    data = data[data['label'] != 'TO_SEE']
    label_dict = {'NONE': 'NONE', 'DISONLY': 'OTHER', 'TREATONLY': 'OTHER', 'PREVENT': 'PREVENT', 'VAGUE': 'OTHER', 'TO_SEE': 'OTHER',
       'TREAT_FOR_DIS': 'CURE', 'SIDE_EFF': 'SIDE_EFF', 'TREAT_NO_FOR_DIS': 'NO_CURE'}
    data = data.replace({'label': label_dict})
    return data
with open('sentences_with_roles_and_relations.txt', encoding = "ISO-8859-1") as f:      #Read in Data
    lines = f.readlines()

def clean_data(sentence):
  tokens = sentence.split()
  for token in tokens:
    if(re.match('<.*?>',token)):
      tokens.remove(token)
  return tokens
def clean_data_2(tokens):
  for token in tokens:
    if(re.match('<.*?>',token)):
      tokens.remove(token)
  return tokens
def add_pos_tags(sentence):
  pos_tags = []
  sen = sp(sentence)
  for i in range(0,len(sen)):
    pos_tags.append(sen[i].pos_)
  return pos_tags
def remove_labels(sentence):
  sentence = re.sub('<.*?>', '',sentence)
  sentence = re.sub('[ \t]+',' ',sentence)
  sentence = sentence.replace(' .','.')
  return sentence.strip()

In [19]:
data_df = pd.DataFrame({'Data':lines})                                                  #Convert to Dataframe
data_df['label'] = data_df['Data'].apply(lambda x: x.split('||')[1].replace('\n', ''))  #Split Label into new column - Y1 Input
data_df['Data'] = data_df['Data'].apply(lambda x: x.split('||')[0].strip())             #Split Data into new column

data_df['Clean Sentence'] = data_df['Data'].apply(lambda x:remove_labels(x))
data_df['Data_Clean'] = data_df['Data'].apply(lambda x: clean_data(x))                  #Remove Tags from Data into new column - X Input
data_df['Data_Clean'] = data_df['Data_Clean'].apply(lambda x: clean_data_2(x))
data_df['Annot'] = data_df['Data'].apply(lambda x: annotate_sentence(x))                #Annotate Sentences - Y2 Input
data_df['Data'].iloc[872] = '<TREATONLY> Primary thrombolytic treatment </TREATONLY> ( within 24 hours of diagnosis ) was given to 169 patients ( 23.5 % ) , whereas the remaining 550 patients were initially treated with <TREATONLY> heparin </TREATONLY> alone .'
data_df = clean_labels(data_df)

label_map = {'NONE':0,"OTHER":1,'PREVENT':2,'CURE':3,'SIDE_EFF':4,'NO_CURE':5}
data_df.replace({'label':label_map},inplace=True)

In [20]:
data_df['label'].value_counts()

0    1818
1     835
3     830
2      63
4      30
5       4
Name: label, dtype: int64

In [21]:
#Limit sampling to 63 examples from each class
cluster_df = data_df[((data_df['label'] == 2) | (data_df['label'] == 4) | (data_df['label'] == 5))]
k = 63

for label in [0, 1, 3]:
  documents_df = data_df[data_df['label'] == label]
  documents_df = documents_df[:k]
  cluster_df = cluster_df.append(documents_df)

cluster_df

Data  ...                                              Annot
26    We conclude that to reduce the rate of <DIS_PR...  ...  [O, O, O, O, O, O, O, O, B-DIS, I-DIS, I-DIS, ...
238   We investigated the hypothesis that <TREAT_PRE...  ...  [O, O, O, O, O, B-TREAT, I-TREAT, I-TREAT, I-T...
374   Our purpose was to systematically review data ...  ...  [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...
381   Appetite suppressants-most commonly <TREAT_SID...  ...  [O, O, O, B-TREAT, O, O, O, O, O, B-DIS, O, O,...
384   Use of <TREAT_SIDE_EFF> fenfluramines </TREAT_...  ...     [O, O, B-TREAT, O, O, O, O, O, O, O, B-DIS, O]
...                                                 ...  ...                                                ...
1759  Randomised trial of <TREAT> roxithromycin </TR...  ...  [O, O, O, B-TREAT, O, B-DIS, I-DIS, I-DIS, O, ...
1762  Randomised study of <TREAT> radical surgery ve...  ...  [O, O, O, B-TREAT, I-TREAT, I-TREAT, I-TREAT, ...
1789  Another use of <TREAT> androgens </TREAT> : tr...  ...  [O, O, O, B-TREAT, O, O, O, B-DIS, I-DIS, I-DI...
1847  <TREAT> Antimicrobial therapy </TREAT> in <DIS...  ...                       [B-TREAT, I-TREAT, O, B-DIS]
1855  <TREAT> Moxonidine </TREAT> for <DIS> hyperten...  ...                             [B-TREAT, O, B-DIS, O]

[286 rows x 5 columns]

In [22]:
cluster_df['label'].value_counts()

3    63
2    63
1    63
0    63
4    30
5     4
Name: label, dtype: int64

In [23]:
#Split dataset into train dev test

bert_RE_input = cluster_df[['Clean Sentence', 'label']]
bert_RE_input.reset_index(drop=True, inplace=True)
r_state = 3
train_df, test_df = train_test_split(bert_RE_input, test_size=0.2, random_state=r_state)
test_df, dev_df = train_test_split(test_df, test_size=0.5, random_state=r_state)
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)
test_df.index.names = ['index']
print(train_df['label'].value_counts())
print(dev_df['label'].value_counts())
print(test_df['label'].value_counts())


3    55
1    53
0    48
2    47
4    23
5     2
Name: label, dtype: int64
2    8
0    8
1    6
3    4
4    3
Name: label, dtype: int64
2    8
0    7
4    4
3    4
1    4
5    2
Name: label, dtype: int64


In [24]:
%%bash
cd biobert/datasets/RE
mkdir medline_input

In [25]:
#create tsv input file
train_df.to_csv('./biobert/datasets/RE/medline_input/train.tsv', sep = '\t', header = False, index = False)
test_df.to_csv('./biobert/datasets/RE/medline_input/test.tsv', sep = '\t', )
dev_df.to_csv('./biobert/datasets/RE/medline_input/dev.tsv', sep = '\t', header = False, index = False)


In [26]:
%%bash
cd biobert
export RE_DIR=./datasets/RE/medline_input
export OUTPUT_DIR=./datasets/RE/medline_input
export TASK_NAME=medline
export BIOBERT_DIR=./biobert_v1.1_pubmed
export model_dir=./biobert_v1.1_pubmed
python medline_run_re.py --task_name=$TASK_NAME --do_train=true --do_eval=true --do_predict=true --vocab_file=$BIOBERT_DIR/vocab.txt --bert_config_file=$BIOBERT_DIR/bert_config.json --init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000 --max_seq_length=128 --train_batch_size=16 --learning_rate=3e-5 --num_train_epochs=10.0 --do_lower_case=false --data_dir=$RE_DIR --output_dir=$OUTPUT_DIR --model_dir=$model_dir





W1202 06:37:38.163672 139948861626240 module_wrapper.py:139] From medline_run_re.py:907: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.


W1202 06:37:38.163896 139948861626240 module_wrapper.py:139] From medline_run_re.py:907: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.


W1202 06:37:38.164356 139948861626240 module_wrapper.py:139] From /content/biobert/modeling.py:92: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.


W1202 06:37:38.165111 139948861626240 module_wrapper.py:139] From medline_run_re.py:938: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for

In [27]:
%%bash
cd biobert
export RE_DIR=./datasets/RE/medline_input
export OUTPUT_DIR=./datasets/RE/medline_input
python ./biocodes/re_eval.py --output_path=$OUTPUT_DIR/test_results.tsv --answer_path=$RE_DIR/test.tsv --task='chemprot'

f1 score    : 82.14%
recall      : 85.19%
precision   : 79.31%


In [28]:
#Results

import sklearn
print('Train_df size', len(train_df))
print('\nLabel Map - ', label_map)
print('Train_df Distribution')
print(pd.DataFrame(train_df['label']).value_counts(sort=False))

results_pd = pd.read_csv('./biobert/datasets/RE/medline_input/test_results.tsv', sep='\t', header=None)
y_pred = [x.index(max(x)) for x in results_pd.values.tolist()]
y_true = test_df['label'].tolist()
print('\nAccuracy', sklearn.metrics.accuracy_score(y_pred,y_true))
print('Confusion Matrix\n', sklearn.metrics.confusion_matrix(y_pred,y_true))
conf_matrix = sklearn.metrics.confusion_matrix(y_pred,y_true)

print('\nLabel Accuracy')
for x in range(len(conf_matrix)):
  print({label_map[x]: x for x in label_map}[[x[0] for x in pd.DataFrame(y_true).value_counts(sort=False).index.values][x]], "{0:.00%}".format(conf_matrix[x][x]/sum([y[x] for y in conf_matrix])),'examples', sum([y[x] for y in conf_matrix]))


print('\nTest_df Distribution')
print(pd.DataFrame(y_true).value_counts(sort=False))


Train_df size 228

Label Map -  {'NONE': 0, 'OTHER': 1, 'PREVENT': 2, 'CURE': 3, 'SIDE_EFF': 4, 'NO_CURE': 5}
Train_df Distribution
label
0        48
1        53
2        47
3        55
4        23
5         2
dtype: int64

Accuracy 0.7931034482758621
Confusion Matrix
 [[5 1 0 0 0 0]
 [1 3 0 0 0 0]
 [0 0 8 0 1 0]
 [0 0 0 4 0 2]
 [1 0 0 0 3 0]
 [0 0 0 0 0 0]]

Label Accuracy
NONE 71% examples 7
OTHER 75% examples 4
PREVENT 100% examples 8
CURE 100% examples 4
SIDE_EFF 75% examples 4
NO_CURE 0% examples 2

Test_df Distribution
0    7
1    4
2    8
3    4
4    4
5    2
dtype: int64


In [29]:
from google.colab import files

output = pd.DataFrame(list(zip(*[y_true,y_pred])))
output.rename(columns={0:'y_true',1:'y_pred'},inplace=True)
output.to_csv('BioBERT_Non_targeted_clustering_without_tags.csv', index=False)
files.download('/content/BioBERT_Non_targeted_clustering_without_tags.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>